todo-queue/01.getting.started/hello_app/config/routes.rb
Rails.application.routes.draw do


  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"

  post "/graphql", to: "graphql#execute"

  resources :high_scores
  get 'articles/index'
  root 'application#hello'
end

todo-queue/01.getting.started/hello_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

todo-queue/01.getting.started/hello_app/app/models/high_score.rb
class HighScore < ApplicationRecord
end

todo-queue/01.getting.started/hello_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    def hello
        render html: "¡Hola, mundo!"
    end
end

todo-queue/01.getting.started/hello_app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

todo-queue/01.getting.started/hello_app/app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = HelloAppSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

todo-queue/01.getting.started/hello_app/app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  before_action :set_high_score, only: [:show, :edit, :update, :destroy]

  # GET /high_scores
  # GET /high_scores.json
  def index
    @high_scores = HighScore.all
  end

  # GET /high_scores/1
  # GET /high_scores/1.json
  def show
  end

  # GET /high_scores/new
  def new
    @high_score = HighScore.new
  end

  # GET /high_scores/1/edit
  def edit
  end

  # POST /high_scores
  # POST /high_scores.json
  def create
    @high_score = HighScore.new(high_score_params)

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to @high_score, notice: 'High score was successfully created.' }
        format.json { render :show, status: :created, location: @high_score }
      else
        format.html { render :new }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_scores/1
  # PATCH/PUT /high_scores/1.json
  def update
    respond_to do |format|
      if @high_score.update(high_score_params)
        format.html { redirect_to @high_score, notice: 'High score was successfully updated.' }
        format.json { render :show, status: :ok, location: @high_score }
      else
        format.html { render :edit }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.json
  def destroy
    @high_score.destroy
    respond_to do |format|
      format.html { redirect_to high_scores_url, notice: 'High score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_score
      @high_score = HighScore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def high_score_params
      params.require(:high_score).permit(:game, :score)
    end
end

todo-queue/01.getting.started/hello_app/app/helpers/application_helper.rb
module ApplicationHelper
end

todo-queue/01.getting.started/hello_app/app/helpers/articals_helper.rb
module ArticalsHelper
end

todo-queue/01.getting.started/hello_app/app/helpers/high_scores_helper.rb
module HighScoresHelper
end

todo-queue/01.getting.started/hello_app/app/views/articles/index.html.erb
<h1>Articals#index</h1>
<p>Find me in app/views/articals/index.html.erb</p>

todo-queue/01.getting.started/hello_app/app/views/high_scores/_form.html.erb
<%= form_with(model: high_score, local: true) do |form| %>
  <% if high_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(high_score.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
        <% high_score.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game %>
    <%= form.text_field :game %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

todo-queue/01.getting.started/hello_app/app/views/high_scores/edit.html.erb
<h1>Editing High Score</h1>

<%= render 'form', high_score: @high_score %>

<%= link_to 'Show', @high_score %> |
<%= link_to 'Back', high_scores_path %>

todo-queue/01.getting.started/hello_app/app/views/high_scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>High Scores</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @high_scores.each do |high_score| %>
      <tr>
        <td><%= high_score.game %></td>
        <td><%= high_score.score %></td>
        <td><%= link_to 'Show', high_score %></td>
        <td><%= link_to 'Edit', edit_high_score_path(high_score) %></td>
        <td><%= link_to 'Destroy', high_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New High Score', new_high_score_path %>

todo-queue/01.getting.started/hello_app/app/views/high_scores/new.html.erb
<h1>New High Score</h1>

<%= render 'form', high_score: @high_score %>

<%= link_to 'Back', high_scores_path %>

todo-queue/01.getting.started/hello_app/app/views/high_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @high_score.game %>
</p>

<p>
  <strong>Score:</strong>
  <%= @high_score.score %>
</p>

<%= link_to 'Edit', edit_high_score_path(@high_score) %> |
<%= link_to 'Back', high_scores_path %>

todo-queue/01.getting.started/hello_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>